# Generated by Django 4.1.7 on 2023-03-20 01:36

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
from wagtail.rich_text import RichText


def convert_to_streamfield(apps, schema_editor):
    BlogPage = apps.get_model("blog", "BlogPage")
    for page in BlogPage.objects.all():
        if page.body.raw_text and not page.body:
            page.body = [("rich_text", RichText(page.body.raw_text))]
            page.save()


def convert_to_richtext(apps, schema_editor):
    BlogPage = apps.get_model("blog", "BlogPage")
    for page in BlogPage.objects.all():
        if page.body.raw_text is None:
            raw_text = "".join(
                [
                    child.value.source
                    for child in page.body
                    if child.block_type == "rich_text"
                ]
            )
            page.body = raw_text
            page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_blogtagindexpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", wagtail.blocks.RichTextBlock())],
                blank=True,
                use_json_field=False,
                verbose_name="Page body",
            ),
        ),
        migrations.RunPython(
            convert_to_streamfield,
            convert_to_richtext,
        ),
    ]
