# Generated by Django 4.1.7 on 2023-03-20 01:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_blogpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", wagtail.blocks.RichTextBlock())],
                blank=True,
                use_json_field=True,
                verbose_name="Page body",
            ),
        ),
    ]
